/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-UlAM4T5cpvRkgvxRMmo1RYXVOS17HJuwMcR9-XVclsDdHEjrj-3bv3R7QsHwhr5r8OTtethlDZIr1kc9Yb4Wq9gaoICXmIfCJ2st2-UA30f1Gu4e3G3upDp-",
  "tt": "tt-1-QWDcCJEWs65AjY3-mqVQZEx6rL84FBW9E3pCeRieH2c=",
  "version": "2020-11-20"
}

export default ebconfig;