/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-get_this_food-fOzj5fBvIuDCofJfuV9N1Zpbv2hmYori",
  "version": "2020-11-20"
}

export default ebconfig;